### PR TITLE
Fix footer nav issue, fix issue with social media icons stretching.

### LINKED ISSUE #71: issue: footer styles are bugged
see image below, should be centered on the footer links

image

### PR DESCRIPTION
**Pull request by manuelosorio**
Closes #71

### CODE REVIEW

**Comment by vincentntang** [comment]
hm viewsource button is skewed left too still 
CleanShot 2023-02-24 at 14 58 57@2x

**Review by chtzvt — APPROVED** [review]
LGTM 👍

**Comment by chtzvt** [comment]
Looks like the images are still warped 😦 

image

**Comment by manuelosorio** [comment]
@chtzvt, that's a different issue that will be handled in a separate PR. Still investigating the cause.

**Comment by chtzvt** [comment]
@manuelosorio Ah! I got them mixed up, my apologies.

**Pull request merged**
