### PR TITLE
Remove duplicate code, cleanup

### LINKED ISSUE #29: REFACTOR - Remove duplicate code between About.njk and Base.NJK files
Both these files have alot of overlapping code. 

- layouts/about.njk
- layouts/base,njk

Suggest moving these into one reusable file called 

- blocks/head.njk

that has the overlapping `<head>` code

AC

- remove the overlapping code used between about.njk and base.njk and move it to one file

### PR DESCRIPTION
**Pull request by manuelosorio**
- Delete layouts/about.njk
- Update layouts/base.njk
- Delete Move large bits of code to their own blocks.
- Fix small syntax errors
- Cleanup comments

closes #29

### CODE REVIEW

**Comment by chtzvt** [comment]
I need to investigate why a preview build wasn’t triggered for this pull request

**Comment by manuelosorio** [comment]
Thank you, let me know if you find out anything about it.

**Comment by chtzvt** [comment]
I have determined the source of the problem. Per the [Cloudflare Pages docs](https://developers.cloudflare.com/pages/platform/known-issues/):

```
Commits/PRs from forked repositories will not create a preview. Support for this will come in the future.
```

**Comment by chtzvt** [comment]
The solution to this would be to add you as a collaborator to this repository, and you can simply work in a branch.

**Pull request closed without merging**
