### PR TITLE
Updates to hamburger menu & font sizes on mobile

### PR DESCRIPTION
**Pull request by iamwill123**
Link to issue: https://github.com/TampaDevs/tampadevs/issues/82
- I believe the hamburger should be on the right on mobile, it's just bette UX.
- Bumped up the font for the dropdown text and height for social icons to match a bit better.

LMK what you think @vincentntang

### CODE REVIEW

**Comment by iamwill123** [comment]
Do we have a staging branch we can deploy to? or any way to preview a PR deployment would be great. If not maybe we can add that feature.
@chtzvt @vincentntang

**Comment by chtzvt** [comment]
@iamwill123 We use Cloudflare Pages, which does preview deployments on every PR. You can see this in action e.g. in #77.

Pages also ran a preview deployment for your pull request, the full status is [here](https://github.com/TampaDevs/tampadevs/pull/83/checks?check_run_id=12195459292), and the live preview is [here](https://481df262.tampadevs.pages.dev/).

**Review by chtzvt — APPROVED** [review]

**Comment by chtzvt** [comment]
This is great, well done. We really appreciate your contribution! 

Your changes will be live on https://www.tampadevs.com in a couple of minutes 🚀 🙏

**Comment by iamwill123** [comment]
@chtzvt thanks for the breakdown, I should've peeked in the `checks` tab, my bad. I'm spoiled with github actions that tell me in the PR, `view deployment` and all that jazz. Appreciate it and no problem, happy to contribute more.

**Pull request merged**
