### PR TITLE
Access Rest APIS with 11ty-fetch

### LINKED ISSUE #51: FEATURE - Add github contributors to the home page, below sponsors/financial backers
Related to notes here for financial contributors on opencollective https://github.com/TampaDevs/tampadevs/issues/50

We should also add a list of github contributors on the homepage who help build out new features

This will be right below all the sponsors and financial contributors. Here's  an example mockup image from React-Hook-Form

image

Not 100% sure how to pull up the list of github contributors, but github should have some tools for doing this

### PR DESCRIPTION
**Pull request by manuelosorio**
- Access Open Collective's API and filter its response to list needed results
- Access Github API to get list of contributors

This will close #51 and goes along with the suggestion @ObieMunoz made.

---
 
This is currently not ready for production and is more intended for further discussion. 

Also need to style it so it can fit in with the rest of the home page.

### CODE REVIEW

**Comment by chtzvt** [comment]
This is looking really solid. Styling aside, I did notice that the GitHub profile links appear to be broken at the moment.

**Comment by chtzvt** [comment]
By the way, Open Collective has a very robust set of widgets they maintain at https://opencollective.com/widgets. How does this approach compare to OC's? 

As an example, I've implemented the OC banner widget on https://tampa.dev.

**Comment by chtzvt** [comment]
Proposing the use of OpenCollective's own widget in #76. Check it out.

**Comment by vincentntang** [comment]
could you redesign and update the content so its more consistent on the page into this PR?

example (e.g. images are a bit bloated)
 
image

effectively make it so we can scale the amount of sections on the page as we add more things

while still making the site consistent

**Comment by chtzvt** [comment]
Closing this PR since the relevant features have been built out/deployed on the site at this point.

**Pull request closed without merging**
